blank_issues_enabled: false
contact_links:
  - name: Bob æŠ€æœ¯æ”¯æŒ
    url: https://bobtranslate.com/general/contact.html
    about: GitHub åé¦ˆæ¸ é“å·²å…³é—­ï¼Œè¯·é€šè¿‡è¿™ä¸ªç½‘é¡µæè¿°çš„æ–¹å¼åé¦ˆé—®é¢˜æˆ–å»ºè®®ã€‚ğŸ™